# Generated by Django 5.0.1 on 2024-01-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_band_active_band_biography_band_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='band',
            name='sold',
            field=models.IntegerField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='band',
            name='type',
            field=models.CharField(choices=[('Record', 'Disque'), ('Clothing', 'Vêtement'), ('Posters', 'Affiches'), ('Miscellaneous', 'Divers')], default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
