# Generated by Django 5.0.1 on 2024-01-31 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_band_description_band_sold_band_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod',
            name='description',
            field=models.TextField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prod',
            name='prix',
            field=models.IntegerField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
