# Generated by Django 5.0.1 on 2024-01-31 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_prod_description_prod_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod',
            name='band',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.band'),
        ),
    ]
