# Generated by Django 5.0.1 on 2024-01-31 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_prod_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prod',
            name='image',
        ),
        migrations.AddField(
            model_name='band',
            name='image',
            field=models.ImageField(default='', upload_to='image'),
            preserve_default=False,
        ),
    ]
