# Generated by Django 5.0.1 on 2024-01-31 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_remove_prod_image_band_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='band',
            old_name='image',
            new_name='images',
        ),
        migrations.AddField(
            model_name='prod',
            name='images',
            field=models.ImageField(default='', upload_to='image'),
            preserve_default=False,
        ),
    ]
